### ISSUE TITLE
Comments on "Crash in image creation at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation"

### ISSUE THREAD

**Issue by LocalJoost** [LocalJoost/BlogComments#355]
Original article: https://localjoost.github.io/Crash-in-image-creation-at-System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation/

**Comment by APlantEatingAnt** [comment]
Thank you for this blog article. It saved me a lot of research today

**Comment by LocalJoost** [comment]
You are welcome  I spent months using the app on a separate machine 😁

**Comment by daveorourke** [comment]
I just wanted to say, on behalf of the Camtasia dev team, thank you for your help (and your friend Rafael too) in finding the root cause for this issue.  Much appreciated!

**Comment by LocalJoost** [comment]
> I just wanted to say, on behalf of the Camtasia dev team, thank you for your help (and your friend Rafael too) in finding the root cause for this issue. Much appreciated!

You are welcome. I am happy to have Camtasia and Resharper working properly at my machine again. I use both extensively.

**Comment by fastudio** [comment]
Many thanks, it happened with NAV client of Business Central 13.... you  saved me from an impossible challenge

**Comment by amp64** [comment]
This also causes the Sonos (and "Sonos S1") app to crash on startup, fantastic to get a work-around.

**Comment by lightstylez** [comment]
Thanks for this. 
I don't know why but this error came up when trying to use a game launcher called "NC Launcher 2" for Blade & Soul. I heard they updated their game engine to Unreal 4 this week, so I wanted to give it a try, but I couldn't open the launcher no matter what I did. I tried 15+ different potential fixes and nothing worked until I found your post. Changing from "SRGB virtual device model profile" to "SRGB IEC61966-2.1" got it to launch just fine.

**Comment by LocalJoost** [comment]
You are welcome. I feel your pain. This is exactly why I wrote the post 😊

**Comment by prorokrak** [comment]
This blog saved my day. Literally. I had similar kind of exception with System.Windows.Media.Imaging.BitmapDecoder in two completely unrelated programs. One of them was Samsung Dex installer (which I did not care about much when it occurred) and the second was NovaMind mind-mapping software (which was really a big problem for me). When I searched for the exception, your blog post was one of the first results.

I messed with color profiles few weeks ago when I received a new monitor, so I tried your approach. And the error immediately disappeared in both pieces of software. So it was like 5 minutes until my problem was solved. I really needed to work with NovaMind, not to spend a day solving technical issues. Thank you very much for sharing this.

**Comment by LocalJoost** [comment]
You are most welcome. I feel your pain 😁 and I am glad this helped to solve it

**Comment by mx3coding** [comment]
Thank you very much!
Man... I tried "everything" to fix my Windows 10... When I found the problem was related with WPF, I was about to reinstall my VS (with so much configuration... ). You saved me !

**Comment by arekdygas** [comment]
Thanks - this helped me as well :)

**Comment by vivaria** [comment]
Thank you so much! This helped me debug an error in a completely different application (Magic: the Gathering Online). Here is the full error log, on the off chance anyone else is searching and comes across this issue:

<details>

```
Application: MTGO.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArithmeticException

Exception Info: System.OverflowException
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.InitializationGuard(System.Xaml.XamlType, System.Object, Boolean)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, Boolean, System.Uri)
   at System.Windows.Markup.XamlReader.Load(System.Xaml.XamlReader, System.Windows.Markup.ParserContext)
   at System.Windows.Markup.XamlReader.Load(System.Xml.XmlReader, System.Windows.Markup.ParserContext, System.Windows.Markup.XamlParseMode, Boolean, System.Collections.Generic.List`1<System.Type>)
   at System.Windows.Markup.XamlReader.Load(System.IO.Stream, System.Windows.Markup.ParserContext, Boolean)
   at MS.Internal.AppModel.AppModelKnownContentFactory.XamlConverterCore(System.IO.Stream, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef, Boolean)
   at MS.Internal.AppModel.MimeObjectFactory.GetObjectAndCloseStreamCore(System.IO.Stream, MS.Internal.ContentType, System.Uri, Boolean, Boolean, Boolean, Boolean, System.Windows.Markup.XamlReader ByRef, Boolean)
   at System.Windows.ResourceDictionary.set_Source(System.Uri)
   at Shiny.App.LoadResources(System.String)
   at Shiny.App.Main()
```

</details>

**Comment by LocalJoost** [comment]
@vivaria you are welcome! 😊
